### ISSUE TITLE
Switch to INI for config

### ISSUE THREAD

**Issue by skuzzymiglet** [Stargarth/Goblocks#5]
Thanks for the great program.

[JSON is not really a config format](https://www.arp242.net/json-config.html).

+ Quoting is difficult, so are the commas
+ Escaping sucks
+ No commenting-out system

I propose INI for a config format. Here's how I'd structure the default config

```ini
[global]

separator = " | "

[weather]
updateSignal = 39
command = (sleep 5 && curl "wttr.in/London?format=3")
timer = 45m

[datetime]
prefix = 🗓
updateSignal = 35
command = #Date		
format = Monday 02/01/2006 15:04:05		
timer = 1s

[volume]
prefix = 🔊 
updateSignal = 36
command = amixer get Master | awk ' /%/ {print $5 $6}' | head -1 | sed -e 's/][/ /g'
timer = 0
prefix = Mem: 
updateSignal = 37
command = "#Memory"
suffix = %
format = %.2f		
timer = 2s

[cpu]
prefix = CPU: 
updateSignal = 38
command = "#Cpu"
suffix = %
format = %.2f		
timer = 2s
```

It would be way easier to comment-out, to change and to create new blocks.

As for implementation, https://github.com/go-ini/ini looks quite good.

What do you think?

**Comment by Ldaxar** [comment]
Hi @skuzzymiglet !

I'm glad that you enjoy it.

> JSON is not really a config format

Neither are c header files :P

> Quoting is difficult, so are the commas
> Escaping sucks

Well, yes and no. Those things are difficult when you are doing them by hand :P. You can use a [json formatter](https://www.freeformatter.com/json-escape.html) to do those things for you. You can also use it to "unescape" commands that you have in config file. If you don't want to be depended on online tools I'm 100% sure that there is a FOSS alternative somewhere.

> No commenting-out system 

Yeah this sucks big time. This is one big drawback of JSON(for config files at least).

However I have chosen JSON format deliberately for two reasons: 
1. It's very lightweight and simple. You can literally write a JSON parser in a single afternoon. 
2. JSON has data structures.

Data structures are super nice because they make transition from file to code seamless. You just unmarshal text from file and you are ready to go. 

I didn't work with ini files but just by looking at API, it has 137 types and functions, while library for JSON has 49 and it is built into go standard.
INI is just a flat map so it would be necessary to add some code to place stuff appropriately. 

I was thinking about YAML for a while, but it looks kinda complex and clunky :/

**Comment by skuzzymiglet** [comment]
I understand the difficulty in Go INI parsing. It does introduce
complexity. I think it's a spectrum - header files are flexible, with a
bunch of types but quite difficult to edit, while config files have
varying levels of flexibility and create more complex code.

Goblocks has simple code and pretty difficult configs. It's about the
balance really. For the ordering problem, perhaps you could have a
module list in `[global]`.

For another parser, I found https://github.com/vaughan0/go-ini. Looks
quite simple, last commit in 2013 though.

Definitely do not do YAML, the tabbing is so difficult and the spec is
massive!

**Comment by Ldaxar** [comment]
> pretty difficult configs

Well, I still don't get what is so difficult about the json config file :P. IMO it's trivial when you use JSON formatter (which is mentioned in README).

**Comment by Ldaxar** [comment]
Hi @skuzzymiglet !

You didn't post any updates for over a week so I'm closing down this issue.

**Comment by skuzzymiglet** [comment]
OK, was thinking about it a bit more. TOML seems like a really good choice for this. INI-like, but with advantages

+ a good parser (https://github.com/BurntSushi/toml)
+ lists
+ standardized

You can have lists (solves that ordering problem)

```
[[block]]

prefix = "CPU "
updateSignal = 35
command = "ls"
timer = "30s"
```

**Comment by Ldaxar** [comment]
Hi @skuzzymiglet !

Sorry for silence, I'm having some time off so I'm almost absent when it comes to my professional stuff 😞.
I think I will stick with JSON for now. However you can (and I see that you did) make a fork and create goblocks version with TOML 😄 .

I just personally think that it's too much effort for little gain. Having no comments in config file is bad, but realistically how  many blocks are you going to have 🤔 ? I guess not more than something between 3 and 10. Besides that, properties that describe each block are easy and you could argue that keys already document them 😉 .

**Comment by skuzzymiglet** [comment]
Thanks for getting back,

+ The commenting is good for temporarily disabling blocks (e.g. if you
switch package manager)
+ There are raw strings in TOML, no more escaping! And multiline too!

Do check https://toml.io/en/ out.

Yes, I did fork. I plan to make some changes, maybe even pull request
some
